apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.info.name }}
  namespace: {{ .Values.info.namespace }}  
  labels:
    app: {{ .Values.info.name }}

spec:
  replicas: {{ .Values.info.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.info.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.info.name }}

    spec:
      automountServiceAccountToken: false
      
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      
      serviceAccountName: {{ .Values.info.name }}-sa

      imagePullSecrets:
        - name: {{ .Values.info.imagePullSecrets }} 

      containers:
        - name: {{ .Values.info.name }}
          image: {{ .Values.info.image }}:{{ .Values.info.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.info.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.info.healthLiveness }}
              port: {{ .Values.info.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.info.healthReadiness }}
              port: {{ .Values.info.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
          command: [ "/usr/bin/krakend" ]
          args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: KRAKEND_PORT
              value: "8080"
          volumeMounts:
            - name: jwk-volume
              mountPath: {{ .Values.vaultAgent.mountPath }}
        - name: vault-agent
          image: {{ .Values.vaultAgent.imageTag }}
          args:
            - "agent"
            - "-config=/vault/config/vault-agent-config.hcl"
          resources:
            {{- toYaml .Values.vaultAgent.resources | nindent 12 }}
          volumeMounts:
            - name: jwk-volume
              mountPath: {{ .Values.vaultAgent.mountPath }}
            - name: vault-agent-config
              mountPath: /vault/config
            - name: vault-agent-template
              mountPath: /vault/templates

      volumes:
        - name: jwk-volume
          emptyDir: {}
        - name: vault-agent-config
          configMap:
            name: {{ .Values.info.name }}-vault-agent-config
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl
        - name: vault-agent-template
          configMap:
            name: {{ .Values.info.name }}-vault-agent-config
            items:
              - key: jwk.tpl
                path: jwk.tpl
