apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.info.name }}
  namespace: {{ .Values.info.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager }}
    
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.info.name }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.info.name }}
                port:
                  number: {{ .Values.info.port }}