apiVersion: v1
description: API Scaffold
name: exm-apins
version: 1.0.0
appVersion: 1.0.0
home: https://example.com
maintainers:
  - name: example-maintainer
    email: example-maintainer@example.com
