info:
  name: &app-name exm-gw-scaffold
  namespace: exm-gwns-dev
  image: ghcr.io/example/exm-gw-scaffold
  tag: sha-xxxxxxx
  imagePullSecrets: dockerconfigjson-github-com
  replicas: 1
  port: 80
  targetPort: 8080
  healthLiveness: /__health
  healthReadiness: /__health

resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 256Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cloud.google.com/gke-spot
              operator: In
              values:
                - "true"
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - *app-name
          topologyKey: kubernetes.io/hostname

tolerations:
  - key: "cloud.google.com/gke-spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

ingress:
  host: api-dev.example.com
  path: /
  certManager: letsencrypt

vaultAgent:
  imageTag: hashicorp/vault:1.21.0
  secretPath: exm-gw-dev/data/exm-gw-scaffold
  mountPath: /etc/krakend/config
  filename: jwk.json
  role: exm-gw-scaffold-role-dev
  url: http://vault-dev.vault-nonprod.svc.cluster.local:8200
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
